### ISSUE TITLE
Adding tests

### ISSUE THREAD

**Issue by christianrondeau** [jawa-the-hutt/lz-string-csharp#10]
Hi! I'm seriously looking at this library, and I am ready to invest some time in improving it. My very first question would be: are you planning on maintaining it? If I do a couple of PR, will you consider them?

The very first thing I would need before changing any code is having a suite of tests. I could create a few basic tests (text with UTF characters, special encoding, etc.) but for this, I would potentially need to create a solution, and depend on something like NUnit.

What do you think? Would you accept a PR that adds tests and a solution? If not, are you open to an alternative?

**Comment by jawa-the-hutt** [comment]
I sent you a PM on gitter.  want to chat with you there about this and the other issues you opened or commented on.

**Comment by christianrondeau** [comment]
Sure, I won't be able to chat right now, but if you're curious: https://github.com/christianrondeau/lz-string-csharp

I tried to include every fork's changes, but I didn't put too much thoughts in pulling back everything yet. I'll try to reach out tomorrow :)

**Comment by christianrondeau** [comment]
Thanks!
