### ISSUE TITLE
possible bug in c# version of compressToBase64

### ISSUE THREAD

**Issue by ReuvenT** [jawa-the-hutt/lz-string-csharp#3]
Hi, 

I've run into a problem in the Base64 encoding method for certain strings - compressed example below. (I included a compressed string instead of the uncompressed to avoid search hits - feel free to decompress it, but please don't post the string). It looks like the enc3 variable needs to be set back to 0 in the loop since it can fall through the if statements and the previous value is used. The fix that worked for me was to add an else to if (!double.IsNaN(chr2) && !double.IsNaN(chr3)) and set enc3 to zero.  

In the original code, the sample string yields "fIo=" at the end, instead of "fIA=".  
"N4IgggDhCqDOCmAnAkgERALgMxYJwEYAaEABUQHsAreAYwBc1MBaIkAeUQHMBDAOwEsAXtzr9yvRhgAMxAGL9EsOgDluAW3iYQAJXgBXAG7xeIYgBluS1Rq0AVRNwBG/E8QCia7vwA2WxHQdnXgABGnFYPW86AAs6WAA6MLVTEDNyThdrTQwQf0CXFMgYBEQAcQo9CEkZHXJveFhMAG0AXWJkWABZSNFO8gATSOyAM25vBHaunv4yKlo6TFHx+GJdDTVHJE6RsYmQWUjvLK1dQ2MAAnsnAoBfIA="

If you could verify and/or provide a correct fix, I'd appreciate it. I'm also curious about the "enc3 = enc4 = 64" statement. Not a common practice in my experience - was that intentional?  

Btw - overall the code has been great and very helpful. We use it for compressing cookies and having the matching compress/decompress methods really make a difference. Thanks!

Reuven

**Comment by jawa-the-hutt** [comment]
Latest commit should address this.

**Comment by a1exb1** [comment]
still not working :s

compressing hello to base64 in c# gives:

BYUwNmD2QAA=

and in JS:


BYUwNmD2Q===
