### ISSUE TITLE
Throwing Actual Exceptions

### ISSUE THREAD

**Issue by szahn** [jawa-the-hutt/lz-string-csharp#4]
Why are the routines in LZString returning the exception message if an exception occurred instead of throw the exception? This doesn't seem like a good practice, especially if one wants to route the logic to an error handler if a routine fails.

Instead of

            catch (Exception ex)
            {
                return ex.Message;
            }

It should be

            catch (Exception ex)
            {
                throw ex;
            }

**Comment by jawa-the-hutt** [comment]
Latest Commit should address this.

https://github.com/jawa-the-hutt/lz-string-csharp/commit/7760c5ce38d30747a54305ec88a11cda72447e4a
