### ISSUE TITLE
Issue decompressing in C# From Encoded URI Component

### ISSUE THREAD

**Issue by Nivas999** [jawa-the-hutt/lz-string-csharp#9]
I am trying to compress data to be sent out of browser using **compressToEncodedURIComponent** method in javascript and I need to decompress it in C# code, I am **not finding the corresponding decompress method decompressFromEncodedURIComponent in C# library**. Please suggest how this can be done.

Please suggest any alternatives for the same to compress in javascript and decompress from C# code.

**Comment by jawa-the-hutt** [comment]
#14 should resolve this.
